_BASE_: "./res50.yaml"
FIND_UNUSED_PARAMETERS: True   # set FIND_UNUSED_PARAMETERS to False when use CHECKPOINT=True for EVA02 backbone
MODEL:
  WEIGHTS: "model_path/GLEE_Pro_scaleup_convert.pth"
  BACKBONE:
    NAME: "D2_EVA02"
  EVA02:
    PRETRAINED_WEIGHT: 'weights/converted_EVA02_m38m_psz14to16.pth'
    IMAGE_SIZE: 1536
    PATCH_SIZE: 16
    WINDOW_SIZE: 16
    DMBED_DIM: 1024
    DEPTH: 24
    NUM_HEADS: 16
    MLP_RATIO: 1
    DROP_PATH_RATE: 0.3
    CHECKPOINT: False
    WINDOW_BLOCK_INDEXES: [ 0, 1, 3, 4, 6, 7, 9, 10, 12, 13, 15, 16, 18, 19, 21, 22 ]
  SEM_SEG_HEAD:
    PIXEL_DECODER_NAME: "MaskDINOEncoder"
    DIM_FEEDFORWARD: 2048
    NUM_FEATURE_LEVELS: 4
    TOTAL_NUM_FEATURE_LEVELS: 4
    IN_FEATURES: ["p3", "p4", "p5", "p6"]
    DEFORMABLE_TRANSFORMER_ENCODER_IN_FEATURES: ["p3", "p4", "p5", "p6"]
    COMMON_STRIDE: 4
    TRANSFORMER_ENC_LAYERS: 6
    FEATURE_ORDER: "low2high"
SOLVER:
  IMS_PER_BATCH: 128
  BASE_LR: 0.0001
  STEPS: (400000,  )
  MAX_ITER: 500000
  WARMUP_ITERS: 1000
  WARMUP_FACTOR: 0.01
  WEIGHT_DECAY: 0.1
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 1.0
  CHECKPOINT_PERIOD: 20000
INPUT:
  IMAGE_SIZE: 1536
  MIN_SCALE: 0.1
  MAX_SCALE: 2.0
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "coco_instance_lsj"
TEST:
  EVAL_PERIOD: 20000
